module.exports = {
    REACT_APP_URL : "/user/login",
    REACT_APP_URLREG :"/user/userSignUp",
    REACT_APP_URLFORGOT : "/user/reset",
    REACT_APP_urlresetpassword : "/user/reset-password",
    REACT_APP_GETNOTES : "/notes/getNotesList",
    REACT_APP_SETNOTES : "/notes/addNotes",
    REACT_APP_SEARCHURLLIST : "/user/searchUserList",
    REACT_APP_ARCHIVENOTELIST : "/notes/getArchiveNotesList",
    REACT_APP_ARCHIVENOTES : "/notes/archiveNotes",
    REACT_APP_UPDATESNOTES : "/notes/updateNotes",
    REACT_APP_DELETENOTES : "/notes/trashNotes",
    REACT_APP_REMOVEREMAINDERNOTES : "/notes/removeReminderNotes",
    REACT_APP_UPDATEREMINDER : "/notes/addUpdateReminderNotes",
    REACT_APP_CHANGECOLOR : "/notes/changesColorNotes",
    REACT_APP_GETREMINDERNOTELIST : "/notes/getReminderNotesList",
    REACT_APP_GETNOTELABELLIST : "/noteLabels/getNoteLabelList",
    REACT_APP_NOTELABELS : "/noteLabels",
    REACT_APP_DELETENOTELABEL : "/deleteNoteLabel",
}