module.exports = {
    REACT_APP_URL : "/user/login",
    REACT_APP_URLREG :"/user/userSignUp",
    REACT_APP_URLFORGOT : "/user/reset",
    REACT_APP_urlresetpassword : "/user/reset-password",
    REACT_APP_GETNOTES : "/notes/getNotesList",
    REACT_APP_SETNOTES : "/notes/addNotes",
    REACT_APP_SEARCHURLLIST : "/user/searchUserList",
    REACT_APP_ARCHIVENOTELIST : "/notes/getArchiveNotesList",
    REACT_APP_ARCHIVENOTES : "/notes/archiveNotes",
    REACT_APP_UPDATESNOTES : "/notes/updateNotes",
    REACT_APP_DELETENOTES : "/notes/trashNotes",
    REACT_APP_REMOVEREMAINDERNOTES : "/notes/removeReminderNotes",
    REACT_APP_UPDATEREMINDER : "/notes/addUpdateReminderNotes",
    REACT_APP_CHANGECOLOR : "/notes/changesColorNotes",
    REACT_APP_GETREMINDERNOTELIST : "/notes/getReminderNotesList",
    REACT_APP_GETNOTELABELLIST : "/noteLabels/getNoteLabelList",
    REACT_APP_NOTELABELS : "/noteLabels",
    REACT_APP_DELETENOTELABEL : "/deleteNoteLabel",
    REACT_APP_ADDLABELNOTES : "/addLabelToNotes",
    REACT_APP_ADDONLY : "/add",
    REACT_APP_SERVICE : "/user/service",
    REACT_APP_LOGOUT : "/user/logout",
    REACT_APP_UPLOADPROFILEIMAGE : "/user/uploadProfileImage",
    REACT_APP_AddcollaboratorsNotes : "AddcollaboratorsNotes",
    REACT_APP_removeCollaboratorsNotes : "removeCollaboratorsNotes",
    REACT_APP_getNotesDetail : "/notes/getNotesDetail/",
    REACT_APP_addQuestionAndAnswer : "addQuestionAndAnswer",
    REACT_APP_questionAndAnswerNotes :"/questionAndAnswerNotes/",
    REACT_APP_getNotesListByLabel : "/notes/getNotesListByLabel/",
    REACT_APP_placeOrder :"/productcarts/placeOrder",
    REACT_APP_myCart :"/productcarts/myCart"

}